# -*- coding: utf-8 -*-
"""s_g3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ow-YgMBYpYsFDurvgyMVKq8FNRtNm3w
"""

import streamlit as st
import pandas as pd
import joblib

# =========================
# Page Configuration
# =========================

st.set_page_config(
    page_title="Student Performance Prediction",
    page_icon="🎓",
    layout="wide"
)

# =========================
# Load Model
# =========================

@st.cache_resource
def load_model():
    model = joblib.load("student_grades_RF.pkl")
    return model

model = load_model()


# =========================
# Title
# =========================

st.title("🎓 Student Performance Prediction")
st.write("Enter the student's information to predict their academic performance.")

st.divider()


# =========================
# Input Form
# =========================

col1, col2 = st.columns(2)

with col1:

    gender = st.selectbox(
        "Gender",
        ["M", "F"]
    )

    nationality = st.selectbox(
        "Nationality",
        [
            "KW",
            "lebanon",
            "Egypt",
            "SaudiArabia",
            "USA",
            "Jordan",
            "venzuela",
            "Iran",
            "Tunis",
            "Morocco",
            "Syria",
            "Palestine",
            "Iraq",
            "Lybia"
        ]
    )

    place_birth = st.selectbox(
        "Place of Birth",
        [
            "KuwaIT",
            "lebanon",
            "Egypt",
            "SaudiArabia",
            "USA",
            "Jordan",
            "venzuela",
            "Iran",
            "Tunis",
            "Morocco",
            "Syria",
            "Palestine",
            "Iraq",
            "Lybia"
        ]
    )

    stage = st.selectbox(
        "Educational Stage",
        [
            "lowerlevel",
            "MiddleSchool",
            "HighSchool"
        ]
    )

    grade = st.selectbox(
        "Grade",
        [
            "G-02",
            "G-04",
            "G-05",
            "G-06",
            "G-07",
            "G-08",
            "G-09",
            "G-10",
            "G-11",
            "G-12"
        ]
    )

    section = st.selectbox(
        "Section",
        ["A", "B", "C"]
    )

    topic = st.selectbox(
        "Topic",
        [
            "IT",
            "Math",
            "Arabic",
            "Science",
            "English",
            "Quran",
            "Spanish",
            "French",
            "History",
            "Biology",
            "Chemistry",
            "Geology"
        ]
    )


with col2:

    semester = st.selectbox(
        "Semester",
        ["F", "S"]
    )

    relation = st.selectbox(
        "Parent Responsible",
        ["Father", "Mum"]
    )

    raisedhands = st.slider(
        "Raised Hands",
        0,
        100,
        50
    )

    visited_resources = st.slider(
        "Visited Resources",
        0,
        100,
        50
    )

    announcements = st.slider(
        "Announcements View",
        0,
        100,
        50
    )

    discussion = st.slider(
        "Discussion",
        0,
        100,
        50
    )

    parent_answer = st.selectbox(
        "Parent Answering Survey",
        ["Yes", "No"]
    )

    parent_satisfaction = st.selectbox(
        "Parent School Satisfaction",
        ["Good", "Bad"]
    )

    absence = st.selectbox(
        "Student Absence Days",
        ["Under-7", "Above-7"]
    )


# =========================
# Prediction Function
# =========================

def prepare_input():

    input_data = {
        "gender": gender,
        "raisedhands": raisedhands,
        "VisITedResources": visited_resources,
        "AnnouncementsView": announcements,
        "Discussion": discussion
    }

    # Get model features
    features = model.feature_names_in_

    # Create DataFrame with all features
    df_input = pd.DataFrame(
        0,
        index=[0],
        columns=features
    )

    # Add gender
    df_input["gender"] = 1 if gender == "M" else 0

    # Add numerical values
    df_input["raisedhands"] = raisedhands
    df_input["VisITedResources"] = visited_resources
    df_input["AnnouncementsView"] = announcements
    df_input["Discussion"] = discussion

    # One Hot Encoding Features
    feature_values = {
        f"NationalITy_{nationality}": 1,
        f"PlaceofBirth_{place_birth}": 1,
        f"StageID_{stage}": 1,
        f"GradeID_{grade}": 1,
        f"SectionID_{section}": 1,
        f"Topic_{topic}": 1,
        f"Semester_{semester}": 1,
        f"Relation_{relation}": 1,
        f"ParentAnsweringSurvey_{parent_answer}": 1,
        f"ParentschoolSatisfaction_{parent_satisfaction}": 1,
        f"StudentAbsenceDays_{absence}": 1
    }

    # Add values if feature exists
    for feature, value in feature_values.items():

        if feature in df_input.columns:
            df_input[feature] = value

    return df_input


# =========================
# Predict Button
# =========================

st.divider()

if st.button("🔮 Predict Student Performance", use_container_width=True):

    try:

        input_df = prepare_input()

        prediction = model.predict(input_df)

        result = prediction[0]

        st.subheader("Prediction Result")

        if result == "H":

            st.success(
                "🎉 High Level Student Performance"
            )

        elif result == "M":

            st.info(
                "📚 Medium Level Student Performance"
            )

        else:

            st.warning(
                "⚠️ Low Level Student Performance"
            )

        st.write("### Predicted Class:", result)

    except Exception as e:

        st.error("An error occurred أثناء التنبؤ")

        st.write(e)


# =========================
# Footer
# =========================

st.divider()

st.caption(
    "🎓 Student Performance Prediction App | Machine Learning Project"
)