# -*- coding: utf-8 -*-
"""student_g.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pl4wqugOV92pM-eAk8aOWzb7yIA7Z113
"""

import pandas as pd
df=pd.read_csv("/content/xAPI-Edu-Data.csv")

df.shape

df.info()

df.isnull().sum()

df.head()

df['gender'].value_counts()

from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

df['gender']=label.fit_transform(df['gender'])
df['Class']=label.fit_transform(df['Class'])

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,5))
plt.title("class by gender")
plt.xlabel("class",fontsize=12)
plt.ylabel("count",fontsize=12)
sns.countplot(data=df,x="Class",hue="gender")
plt.show()

plt.figure(figsize=(4,4))
plt.title("nationalities")
plt.pie(df['NationalITy'].value_counts(),
        labels=df['NationalITy'].value_counts().index,
        colors=sns.color_palette('dark'),
)
plt.show()

df.info()

object_columns = df.select_dtypes(include='object').columns

df = pd.get_dummies(df, columns=object_columns, drop_first=True)

df.info()

from sklearn.model_selection import train_test_split
x=df.drop(columns='Class')
y=df['Class']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

result=model.predict(x_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,result)
print("النتيجة هي :",score)

from sklearn.linear_model import LogisticRegression

model2 = LogisticRegression()
model2.fit(x_train, y_train)

result2 = model2.predict(x_test)
accuracy_score(y_test, result2)

import joblib as jb
joblib.dump(model, 'model.joblib')

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

model = RandomForestClassifier(random_state=42)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy %:", accuracy * 100)

import joblib as jb
joblib.dump(model, 'model.joblib')