# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ow-YgMBYpYsFDurvgyMVKq8FNRtNm3w
"""

# 4. تحويل المدخلات إلى Vector بنفس الـ 60 Feature المتوقعة للموديل
def prepare_features():
    # قائمة الـ 60 ميزة كما هي في الموديل
    feature_names = [
        'gender', 'raisedhands', 'VisITedResources', 'AnnouncementsView', 'Discussion',
        'NationalITy_Iran', 'NationalITy_Iraq', 'NationalITy_Jordan', 'NationalITy_KW',
        'NationalITy_Lybia', 'NationalITy_Morocco', 'NationalITy_Palestine',
        'NationalITy_SaudiArabia', 'NationalITy_Syria', 'NationalITy_Tunis',
        'NationalITy_USA', 'NationalITy_lebanon', 'NationalITy_venzuela',
        'PlaceofBirth_Iran', 'PlaceofBirth_Iraq', 'PlaceofBirth_Jordan',
        'PlaceofBirth_KuwaIT', 'PlaceofBirth_Lybia', 'PlaceofBirth_Morocco',
        'PlaceofBirth_Palestine', 'PlaceofBirth_SaudiArabia', 'PlaceofBirth_Syria',
        'PlaceofBirth_Tunis', 'PlaceofBirth_USA', 'PlaceofBirth_lebanon',
        'PlaceofBirth_venzuela', 'StageID_MiddleSchool', 'StageID_lowerlevel',
        'GradeID_G-04', 'GradeID_G-05', 'GradeID_G-06', 'GradeID_G-07',
        'GradeID_G-08', 'GradeID_G-09', 'GradeID_G-10', 'GradeID_G-11',
        'GradeID_G-12', 'SectionID_B', 'SectionID_C', 'Topic_Biology',
        'Topic_Chemistry', 'Topic_English', 'Topic_French', 'Topic_Geology',
        'Topic_History', 'Topic_IT', 'Topic_Math', 'Topic_Quran',
        'Topic_Science', 'Topic_Spanish', 'Semester_S', 'Relation_Mum',
        'ParentAnsweringSurvey_Yes', 'ParentschoolSatisfaction_Good',
        'StudentAbsenceDays_Under-7'
    ]

    # قاموس لإدراج القيم (افتراضياً 0)
    data = {feat: 0 for feat in feature_names}

    # ملء القيم الأعدادية والجنس
    data['gender'] = 1 if gender == "Female" else 0
    data['raisedhands'] = raisedhands
    data['VisITedResources'] = visited_resources
    data['AnnouncementsView'] = announcements_view
    data['Discussion'] = discussion

    # ملء الـ One-Hot Encoded Features
    if f"NationalITy_{nationality}" in data:
        data[f"NationalITy_{nationality}"] = 1
    if f"PlaceofBirth_{nationality}" in data:  # افتراض مكان الميلاد بنفس الجنسية
        data[f"PlaceofBirth_{nationality}"] = 1

    if f"StageID_{stage}" in data:
        data[f"StageID_{stage}"] = 1

    if f"GradeID_{grade}" in data:
        data[f"GradeID_{grade}"] = 1

    if f"SectionID_{section}" in data:
        data[f"SectionID_{section}"] = 1

    if f"Topic_{topic}" in data:
        data[f"Topic_{topic}"] = 1

    data['Relation_Mum'] = 1 if relation == "Mum" else 0
    data['ParentAnsweringSurvey_Yes'] = 1 if parent_survey == "Yes" else 0
    data['ParentschoolSatisfaction_Good'] = 1 if parent_sat == "Good" else 0
    data['StudentAbsenceDays_Under-7'] = 1 if student_absence == "Under-7" else 0

    # تحويل القاموس إلى مصفوفة 2D متناسبة مع scikit-learn
    return np.array([list(data.values())])

# 5. زر التنبؤ
st.markdown("---")
if st.button("🚀 تشغيل الموديل وإخراج النتيجة", use_container_width=True):
    features = prepare_features()

    # إجراء التنبؤ
    prediction = model.predict(features)

    st.success(f"نتيجة التنبؤ للموديل: {prediction[0]}")